Update dip-0006.md
dashpay/dips pull request #109
Opened 2022-03-31 11:55 UTC by VirgileBa

a llmqType was forgotten in the hash, now it reflects the codebase

2022-04-05 22:10 UTC, UdjinM6 requested changes

2022-04-06 10:41 UTC, VirgileBa commented on dip-0006.md
> +2. Calculate `SHA256(proTxHash, quorumHash, llmqType)` for each entry in the list
how do the documentation even end up being that far from what's actually implemented?

2022-04-06 15:11 UTC, UdjinM6 commented on dip-0006.md
> +2. Calculate `SHA256(proTxHash, quorumHash, llmqType)` for each entry in the list
🤷‍♂️

2022-04-08 08:19 UTC, ogabrielides approved these changes

2022-04-08 09:31 UTC, UdjinM6 approved these changes
LGTM 👍

2022-04-08 16:22 UTC, merged

2022-04-15 12:49 UTC, ogabrielides commented
@UdjinM6 Looks like `modifier = SHA256(SHA256(llmqType, quorumHash))` (double SHA256 instead of single).
Check implementation of `::SerializeHash` used to build `modified`.