docs: update DIP6 LLMQ types table
dashpay/dips pull request #114
Opened 2022-07-07 15:42 UTC by thephez

Adds newer testing LLMQ types from v17/v18

2022-07-07 17:18 UTC, ogabrielides approved these changes
LGTM

2022-07-11 21:27 UTC, UdjinM6 requested changes

2022-07-11 21:27 UTC, UdjinM6 commented on dip-0006/llmq-types.md
> +| LLMQ_DEVNET_DIP0024 | 105 | 8 | 6 | 4 (50%) | 24 (1 Hour) | 2 | 7 | 2 | For devnets only |
```suggestion
| LLMQ_DEVNET_DIP0024 | 105 | 8 | 6 | 4 (50%) | 48 (2 Hours) | 2 | 7 | 2 | For devnets only |
```

2022-07-11 21:34 UTC, UdjinM6 approved these changes
👍

2022-07-12 07:06 UTC, ogabrielides approved these changes

2022-07-12 13:53 UTC, merged