feat: add invite funding key derivation path
dashpay/dips pull request #140
Opened 2023-08-02 22:39 UTC by HashEngineering

This PR will add invite funding key derivation paths to DIP13.

2023-08-03 16:48 UTC, thephez requested changes

2023-08-03 16:48 UTC, thephez commented on dip-0013.md
> +Identity Invitation Funding keys used to fund invites and are the fourth sub feature for Blockchain Identities. They are always derived as ECDSA keys.
```suggestion
Identity Invitation Funding keys used to fund invites are the fourth sub feature for Blockchain Identities. They are always derived as ECDSA keys.
```

2023-08-03 16:48 UTC, thephez commented on dip-0013.md
> +`m / purpose' / coin_type' / feature' / sub feature' / funding index' /`
```suggestion
We define the following levels for them:

`m / purpose' / coin_type' / feature' / sub feature' / funding index' /` 
```

2023-08-03 16:48 UTC, thephez commented on dip-0013.md
> +attempt reuse it.  Dash Platform can be queried to see if the invitation funding transaction
```suggestion
attempt reusing it.  Dash Platform can be queried to see if the invitation funding transaction 
```

2023-08-03 16:53 UTC, thephez commented
This should also update the DIP-9 table: https://github.com/dashpay/dips/blob/master/dip-0009/assignments.md

2023-09-18 20:15 UTC, HashEngineering commented
@thephez I have made the requested changes.

2023-09-22 12:59 UTC, HashEngineering commented on dip-0009/assignments.md
> +| `5'` | Identity Keys | [DIP 0013: Identities in Hierarchical Deterministic wallets](../dip-0013.md) | The related keys are located in the following sub-paths: <br>`0'/key type'/identity index'/key
I made these changes in the most recent commit, @thephez

2023-09-25 12:36 UTC, thephez requested changes
Can you also update the table of contents to include the new section? I just noticed it wasn't included there.

2023-12-19 20:12 UTC, HashEngineering commented
@thephez I finally updated the PR based on your latest comments.

2023-12-20 14:12 UTC, thephez commented on dip-0013.md
> +Identity Invitation Funding keys used to fund invites are the fourth sub feature for Blockchain Identities. They are always derived as ECDSA keys.
For consistency
```suggestion
Identity Invitation Funding keys used to fund invites are the fourth sub feature for identities. They are always derived as ECDSA keys.
```

2023-12-20 15:44 UTC, thephez requested changes
A few more minor ones :slightly_smiling_face:

2023-12-20 15:44 UTC, thephez commented on dip-0013.md
> +attempt reusing it.  Dash Platform can be queried to see if the invitation funding transaction
```suggestion
attempt reusing it. Dash Platform can be queried to see if the invitation funding transaction 
```

2023-12-20 15:44 UTC, thephez commented on dip-0013.md
> +has been used.  It will be up to the user to determine if the invite should be resent to the original
```suggestion
has been used. It will be up to the user to determine if the invite should be resent to the original 
```

2023-12-20 15:44 UTC, thephez commented on dip-0013.md
> +Identity Invitation Funding keys used to fund invites are the fourth sub feature for identities. They are always derived as ECDSA keys.
```suggestion
Identity Invitation Funding keys used to fund invites are the fourth sub-feature for identities. They are always derived as ECDSA keys.
```

2023-12-20 21:24 UTC, thephez submitted a review, later dismissed
Looks fine to me :+1:

2025-05-21 20:24 UTC, merged