docs(DIP29): random beacon for llmq selection
dashpay/dips pull request #143
Opened 2023-09-04 13:09 UTC by thephez

This DIP proposes leveraging DVRFs (Decentralized [Verifiable Random Functions](https://en.wikipedia.org/wiki/Verifiable_random_function)) to create decentralized randomness inside the Dash ecosystem in a secure, verifiable manner.

2023-09-04 17:37 UTC, ogabrielides requested changes

2023-09-04 17:37 UTC, ogabrielides commented on dip-0029.md
> +`[h, CB_CL(h), H_diff(h)`], `[h+1, CB_CL(h+1), H_diff(h+1)]` is a valid succession as long as
`[h, CB_CL(h), H_diff(h)]`

2023-09-14 14:57 UTC, ogabrielides approved these changes
LGTM

2023-09-26 14:27 UTC, UdjinM6 approved these changes
LGTM

2023-10-05 09:31 UTC, VirgileBa approved these changes

2023-11-07 14:17 UTC, PastaPastaPasta approved these changes

2023-11-07 14:19 UTC, PastaPastaPasta approved these changes

2023-11-07 14:22 UTC, ogabrielides approved these changes
re-ACK

2023-11-07 14:45 UTC, merged