chore: DIP4 Adjusted Coinbase description to v20
dashpay/dips pull request #148
Opened 2023-11-10 14:35 UTC by ogabrielides

Added changes brought by DIP-29 and DIP-27 to Coinbase.

2023-11-13 13:28 UTC, thephez requested changes

2023-11-13 13:28 UTC, thephez commented on dip-0004.md
> +More information on the field `creditPoolBalance` can be found in [DIP0027 - Platform Credit Funding and Withdrawals](https://github.com/dashpay/dips/blob/master/dip-0027.md).
Let's leave out a link for now and add it once it's available.
```suggestion
More information on the `creditPoolBalance` field will be described in a future document.
```

2023-11-13 15:55 UTC, thephez commented on dip-0004.md
> +| creditPoolBalance | int64_t | 8 | Total amount Dash Platform credits locked at the block height. |
This balance is denominated in DASH so maybe smth like this?
```suggestion
| creditPoolBalance | int64_t | 8 | Total amount DASH currently locked as of this block height. |
```

2023-11-13 15:56 UTC, thephez commented on dip-0004.md
> +| creditPoolBalance | int64_t | 8 | Total amount of locked credits at the block height. |
Confirmed on slack that this is DASH denominated

2023-11-13 20:40 UTC, knst approved these changes
LGTM

2023-11-14 13:14 UTC, UdjinM6 approved these changes

2023-11-15 19:06 UTC, thephez approved these changes

2023-11-15 19:06 UTC, merged