DIP0008: Replace signing attempts with a majority of quorums singing the same height
dashpay/dips pull request #85
Opened 2021-02-26 11:18 UTC by UdjinM6

The main idea is to let all active ChainLock quorums create new CLSIG messages at every block and to require the majority of these quorums to vote for the same hash to actually lock the chain. Unlike in current system, having a malicious quorum will no longer be enough to disrupt ChainLocks via withholding attack or by producing "fake" CLSIGs (CLSIGs for some future height with some random hashes). This also deprecates the "signing attempts" part cause it feels redundant in this setup.

PoC for Dash Core: https://github.com/dashpay/dash/pull/4016

2021-03-09 23:17 UTC, xdustinface requested changes
Good idea 👍 I didn't think that much about the details/impact yet but overall i think it makes sense, see comments below for some thoughts after a first read + [table-of-contents](https://github.com/dashpay/dips/blob/57d4cf215678ad8403fcdf8f935c65138548918d/dip-0008.md#table-of-contents) section also needs some adjustments :) e.g. this dead link -> [signing-attempts](https://github.com/dashpay/dips/blob/57d4cf215678ad8403fcdf8f935c65138548918d/dip-0008.md#signing-attempts)

Also, did you think about just making a separate DIP out of this? I honestly don't have a strong opinion on wether it should be separate or not but i think it could make sense to make a new and refer to this one. Thoughts?

2021-03-09 23:17 UTC, xdustinface commented on dip-0008.md
> +  3. A quorum must be selected from the set based on the calculated request id.
```suggestion
  1. Based on the deterministic masternode list at the given height,
  the set of active quorums must be calculated.
  2. The request id must be calculated.
  3. The quorum must be selected from the set based on the calculated request id.
```

Might be only me but `A/a` sounds like there could be multiple but there can only be one of those for the specific height, no?

2021-03-09 23:17 UTC, xdustinface commented on dip-0008.md
> +  3. A `step`th quorum must be selected from the set.
```suggestion
  1. Based on the deterministic masternode list at the given height,
  the set of active quorums must be calculated.
  2. The request id must be calculated using the bit in the `signers` bitset set to `1` as a `step`.
  3. The `step`th quorum must be selected from the set.
```
Like above

2021-03-09 23:17 UTC, xdustinface commented on dip-0008.md
> +  a set of active quorums must be calculated.
```suggestion
  the set of active quorums must be calculated.
```

2021-03-09 23:17 UTC, xdustinface commented on dip-0008.md
> +  a set of active quorums must be calculated.
Same

2021-03-09 23:47 UTC, UdjinM6 commented on dip-0008.md
> +The message hash is always the hash of the signed block.
Signing is done via an interface defined in DIP0007, mentioned this in 2effb4d.

(side note: DIP0007 needs updating...)

2021-03-10 00:06 UTC, UdjinM6 commented on dip-0008.md
> +After a LLMQ member has successfully recovered the final ChainLocks signature
This part is basically a copy/paste from the original text https://github.com/dashpay/dips/pull/85/files#diff-93e810c1866c9c5a380149d70483041dba93c8b2c274945b9313813a7e4ab10bR153 and I think in this case we refer to ChainLocks as a technology (as defined in `Abstract`), not as an individual object (the object is the signature here).

2021-03-10 00:15 UTC, xdustinface commented on dip-0008.md
> +    1.  [Signing blocks using multiple LLMQs](#signing-blocks-using-single-llmqs)
```suggestion
    1.  [Signing blocks using multiple LLMQs](#signing-blocks-using-multiple-llmqs)
```

2021-03-10 00:17 UTC, UdjinM6 commented on dip-0008.md
> +    1.  [Signing blocks using multiple LLMQs](#signing-blocks-using-single-llmqs)
ooops, fixed

2021-03-10 01:28 UTC, QuantumExplorer commented
I'm not sure I understand the reasoning behind this change. Could you elaborate more @UdjinM6? Taking control of a 400 member quorum requires close to 60% of the network or 50% and a lot of hash power.

2021-03-10 09:59 UTC, QuantumExplorer commented on dip-0008.md
> +The node should ensure that the fully singed block is locally accepted as the
signed

2021-03-12 03:31 UTC, xdustinface requested changes
For me the `step` stuff looks a bit confusing tbh, thoughts about c0648013f3a3daf93bf67f36d41ea41d8fa6b9af? See xdustinface/dash@36628cf40f392b4f204dab239ac33a85064b2b38 for an implementation of it.

2021-03-12 08:03 UTC, UdjinM6 commented
@xdustinface Makes sense, picked both. Thanks! 👍

2021-03-12 13:35 UTC, xdustinface requested changes
Some more (and my last) points: 
- Let's maybe just move the signer stuff into the table like in 3f02341?
- Maybe we should mention somewhere that the value of `SPORK_19_CHAINLOCKS_ENABLED` is used to decide if multi LLMQ signing is enabled or not. 
- It looks like there is a mismatch between dashpay/dash#4016 and the changes here. For me when i read it here it sounds like:
     - If single LLMQ signing is enabled, i.e. the spork is active and != 1, the `CLSIG` has structure `A` (signers fields are not present)
     - If multi LLMQ signing is enabled, i.e. the spork value is 1, the `CLSIG` has structure `B` (signer fields present).

  But it's actually always structure `B` with protocol version `70220` but with signers size 0, no? So we could maybe merge those both tables, put them somewhere (maybe a separate message section) below the signing section and somehow mark the new fields introduced by the new version. Thoughts?

2021-03-15 11:04 UTC, xdustinface approved these changes
Looks all good to me now 👍

2021-03-15 14:22 UTC, thephez commented on dip-0008.md
> +There are two possible ways to form a ChainLock: using single LLMQ and using
```suggestion
There are two possible ways to form a ChainLock: using a single LLMQ and using
```

2021-03-15 14:22 UTC, thephez commented on dip-0008.md
> +nodes if necessary. If an alternative block for the same height is received,
Suggested rewording of this sentence:

If the correct block is already present locally and an alternative block for the same height is received, the alternative block must not be added to the currently active chain.

2021-03-15 14:28 UTC, thephez commented
Is the "Calculations" section still accurate with this change? Also, I was thinking it might be nice to include a link to the original version of the document (whatever the most recent change was) so people can easily refer back to it. I think that could be added to the "Prior Work" section.

2021-03-15 16:26 UTC, UdjinM6 commented on dip-0008.md
> +already present locally.
```suggestion
nodes if necessary. If the correct block is already present locally and an alternative block for the same height is received, the alternative block must not be added to the currently active chain.
```

2021-03-15 16:52 UTC, UdjinM6 commented
> Is the "Calculations" section still accurate with this change?

Should be accurate for a single LLMQ mode but yeah, for a multi-quorum mode you'd need to disrupt or control 2 quorums at the same time so I guess you should take all these probabilities roughly to the power of 2 or so? Let's ping @DarrenTa :)

> Also, I was thinking it might be nice to include a link to the original version of the document (whatever the most recent change was) so people can easily refer back to it. I think that could be added to the "Prior Work" section.

Hmm... current version in master is https://github.com/dashpay/dips/blob/81e81b52799114191729364ed36dc0e372062fbe/dip-0008.md but I'm not sure if it makes a lot of sense to link back to itself, especially in a git repo..

2021-03-16 12:36 UTC, DarrenTa commented
Thank you so much for the ping.  I can provide the following:

1)  I can review this change and form an opinion, backed by data, if this should be live or not.
2)  I do agree with @QuantumExplorer above.  I would want a comparable security level out of the new process.  
3)  I almost wonder if a **straight up multisig** would be the way to go?  The threshold setup does require overhead.
4)  In response to @thephez perhaps DIP0008 should not be edited at all.  It would be best to make a new DIP and then change the status of 0008 (to something like superseded).

I have cited DIP0008 in my academic work, it would make my citations cleaner if DIP0008 was not changed significantly.  I was lazy and did not put date accessed.

I've also cited (withdrawn) 0005 and think the citations provide for a robust discussion, even if not live.  No reason 0008 has to be edited to agree with the live implementation.

I'll circle back here in a week and report back with a proper analysis.

2021-03-16 14:27 UTC, UdjinM6 commented
Hmm.. ok, you convinced me to at least create an alternative PR to have smth to compare to :) Pls see #89.

2021-03-17 15:37 UTC, UdjinM6 commented
closing in fav of #89

2021-03-17 15:37 UTC, closed without merging