Draft: dash tx value signing
dashpay/dips pull request #95
Opened 2021-07-20 15:46 UTC by mayoreee

This DIP describes a digest algorithm that implements the signature covers value when signing Dash transactions. 
It opens the path for more efficient signing of Dash transactions on hardware wallets.

2021-07-22 19:26 UTC, thephez requested changes
A few initial comments.

2021-07-22 19:26 UTC, thephez commented on dash-tx-value-signing.md
> +This DIP describes a digest algorithm that implements the signature covers value when signing Dash transactions. It opens the path for more efficient signing of Dash transactions on hardware wallets.
The first sentence is not very clear to me. Looks like it may be part of 2 sentences that got mixed together during editing?

2021-07-22 19:26 UTC, thephez commented on dash-tx-value-signing.md
> +* The algorithm does not involve the amount of DASH being spent by the input. This is usually not a problem for online network nodes as they could request for the specified transaction to acquire the
```suggestion
* The algorithm does not involve the amount of DASH being spent by the input. This is usually not a problem for online network nodes as they could request the specified transaction to acquire the output value. For an offline transaction signing device (cold wallet"), however, not knowing the input amount makes it impossible to calculate the exact amount being spent and the transaction fee. To cope with this problem, a cold wallet must also acquire the full transaction being spent, which could be a big obstacle in the implementation of lightweight, air-gapped wallet. By including the input value of part of the transaction digest, a cold wallet may safely sign a transaction by learning the value from an untrusted source. In the case that a wrong value is provided and signed, the signature would be invalid and no funding would be lost. See [SIGHASH_WITHINPUTVALUE: Super-lightweight HW wallets and offline data](https://bitcointalk.org/index.php?topic=181734.0).
```

2021-07-22 19:26 UTC, thephez commented on dash-tx-value-signing.md
> +  The serialized signed transaction is: 01000000000102fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f00000000494830450221008b9d1dc26ba6a9cb62127b02742fa9d754cd3bebf337f7a55d114c8e5cd
Not sure if this matters (perhaps @UdjinM6 or @PastaPastaPasta can provide input), but this isn't a valid Dash transaction. Putting it into `decoderawtransaction` returns `TX decode failed (code -22)`. It appears that this is just the example for a Native P2WPKH tx from [BIP-143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#native-p2wpkh).

2021-07-29 22:29 UTC, UdjinM6 requested changes

2021-07-29 22:29 UTC, UdjinM6 commented on dash-tx-value-signing.md
> +Title: Transaction value signing analogous to BIP143 as implemented in Bitcoin Cash
This mentions Bitcoin Cash yet there is no link to the corresponding spec (https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/replay-protected-sighash.md ?) and in general it looks more like bip143 with segwit related parts removed.

2021-07-29 22:29 UTC, UdjinM6 commented on dash-tx-value-signing.md
> +# Specification
The upgrade path is not described: btc used segwit as an activation path and bch used `SIGHASH_FORKID`+`SCRIPT_ENABLE_SIGHASH_FORKID` https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/replay-protected-sighash.md#activation. What is the proposed way to activate this DIP in Dash?

2021-08-17 10:56 UTC, mayoreee commented
@thephez  Yes, I'm still looking into the issues raised. I'll push some changes soon.

2022-08-24 23:53 UTC, closed without merging